"""Text rendered into agent files. Kept short on purpose: every byte here can be
loaded into a model context (budgets are enforced by tests)."""

from __future__ import annotations

GENERATED_NOTE = (
    "<!-- Generated by ai-governance. Change it with `ai-governance update`; "
    "local edits are kept and reported. -->"
)

GLOBAL_INSTRUCTIONS = """\
# ai-governance
- Deterministic tools first: `ws run -- <cmd>` (condensed output + `ws log <id>` for more),
  `ws check --changed`, `ws detect`, `ai-governance progress here|show|step|fact`,
  `ai-governance jira|confluence`. Never re-run a command just to see more of its output.
- Frugal reads: `git diff --stat` before `git diff`; `git log --oneline -n 10`; pipe JSON
  through `jq` with a minimal projection; read large files with offset/limit; never print
  lockfiles, bundles or generated files.
- Delegate broad exploration, file reading, summaries and web research to the `scout`
  subagent (cheaper model); verify critical claims yourself before acting on them.
- Executing an approved plan: heavy implementation -> mid-tier subagent, tests/docs/
  mechanical edits -> cheapest tier; you review each delivery and run the gates per phase.
- Never write "honest"/"honestly" (es: "honesto"/"honestamente"); state caveats directly.
"""

PROJECT_BLOCK = """\
## AI governance
- Engineering rules live once in {rule_locations} and load per file in every agent
  (Claude Code reads them through symlinks in `.claude/rules/`); do not read them manually.
- Run builds and tests with `ws run -- <cmd>` and the gate with `ws check --changed`.
- Delegate exploration, reading, summaries and web research to the `scout` subagent.
- Track multi-session work with `ai-governance progress`.
"""

SCOUT_DESCRIPTION = (
    "Read-only scout for broad exploration, file reading, summaries and web research. "
    "Use it instead of reading many files or searching the web in the main session."
)

SCOUT_INSTRUCTIONS = """\
You are a read-only scout. Explore, read, summarize or research exactly what was asked.
- Never modify files or run commands with side effects.
- Report compactly: findings first, each backed by `path:line` or a URL.
- Say explicitly when something is uncertain or was not found; never guess.
- Stay under ~400 words unless asked for more.
"""

PROGRESS_SKILL = """\
---
name: progress
description: Resume, record and close multi-session work with the ai-governance progress tracker.
---
# Progress tracking

Use the compact tracker instead of re-reading history:

- `ai-governance progress here` — task bound to the current repository/branch.
- `ai-governance progress show <task-id>` — compact state (`--full` adds the log).
- `ai-governance progress new <task-id> --title "..."` — start a task.
- `ai-governance progress step <task-id> add|done "<text>"` — plan and tick steps.
- `ai-governance progress fact <task-id> "<text>"` — record a durable decision or finding.
- `ai-governance progress close <task-id> --reason "..."` — finish.

Record only what a future session needs: decisions, next step, blockers.
"""
