"""Text rendered into agent files. Kept short on purpose: every byte here can be
loaded into a model context (budgets are enforced by tests)."""

from __future__ import annotations

GENERATED_NOTE = (
    "<!-- Generated by ai-governance. Change it with `ai-governance update`; "
    "local edits are kept and reported. -->"
)

GLOBAL_INSTRUCTIONS = """\
# ai-governance
- Deterministic tools first: `ws run -- <cmd>` (condensed output + `ws log <id>` for more),
  `ws check --changed`, `ws detect`, `ai-governance progress here|show|step|fact`,
  `ai-governance jira|confluence`. Never re-run a command just to see more of its output.
- Frugal reads: `git diff --stat` before `git diff`; `git log --oneline -n 10`; pipe JSON
  through `jq` with a minimal projection; read large files with offset/limit; never print
  lockfiles, bundles or generated files.
- Delegate exploration, file reading and summaries to the `scout` subagent and web
  research to `researcher` (else `scout`); verify critical claims yourself before acting.
- Executing an approved plan: heavy implementation -> mid-tier subagent, tests/docs/
  mechanical edits -> cheapest tier; you review each delivery and run the gates per phase.
- Never write "honest"/"honestly" (es: "honesto"/"honestamente"); state caveats directly.
"""

PROJECT_BLOCK = """\
## AI governance
- Engineering rules live once in {rule_locations} and load per file in every agent
  (Claude Code reads them through symlinks in `.claude/rules/`); do not read them manually.
- Run builds and tests with `ws run -- <cmd>` and the gate with `ws check --changed`.
- Delegate exploration, reading, summaries and web research to the `scout` subagent.
- Track multi-session work with `ai-governance progress`.
"""

SCOUT_DESCRIPTION = (
    "Read-only scout for broad exploration, file reading, summaries and web research. "
    "Use it instead of reading many files or searching the web in the main session."
)

# Claude splits the scout: code reading on the cheapest model, web research on a mid tier
# (synthesizing and checking sources is where a cheap model mixes up facts).
CLAUDE_SCOUT_DESCRIPTION = (
    "Read-only scout for broad codebase exploration, file reading and summaries. "
    "Use it instead of reading many files in the main session; for web research use `researcher`."
)

RESEARCHER_DESCRIPTION = (
    "Read-only web researcher: searches and reads sources, compares options and separates "
    "verified facts from guesses. Use it instead of searching the web in the main session."
)

RESEARCHER_INSTRUCTIONS = """\
You are a read-only web researcher. Research exactly what was asked.
- Never modify files or run commands with side effects.
- Prefer primary sources (official docs, repos, release pages); note dates and versions.
- Report compactly: findings first, each backed by a URL.
- Mark clearly what you could not verify; never guess.
- Stay under ~400 words unless asked for more.
"""

SCOUT_INSTRUCTIONS = """\
You are a read-only scout. Explore, read, summarize or research exactly what was asked.
- Never modify files or run commands with side effects.
- Report compactly: findings first, each backed by `path:line` or a URL.
- Say explicitly when something is uncertain or was not found; never guess.
- Stay under ~400 words unless asked for more.
"""

# Antigravity tiers are inherit|flash|pro; `flash` is always the latest Gemini Flash.
# Read-only: a misspelled tool name can hang the subagent, so `probe` uses these too.
ANTIGRAVITY_SCOUT_SETTINGS = (
    "model: flash\n"
    "tools:\n"
    "  - view_file\n"
    "  - grep_search\n"
    "  - find_by_name\n"
    "  - list_dir\n"
    "commandExecutionPolicy: off\n"
)

PROGRESS_SKILL = """\
---
name: progress
description: Resume, record and close multi-session work with the ai-governance progress tracker.
---
# Progress tracking

Use the compact tracker instead of re-reading history:

- `ai-governance progress here` — task bound to the current repository/branch.
- `ai-governance progress show <task-id>` — compact state (`--full` adds the log).
- `ai-governance progress new <task-id> --title "..."` — start a task.
- `ai-governance progress step <task-id> add|done "<text>"` — plan and tick steps.
- `ai-governance progress fact <task-id> "<text>"` — record a durable decision or finding.
- `ai-governance progress close <task-id> --reason "..."` — finish.

Record only what a future session needs: decisions, next step, blockers.
"""

TEST_AUDIT_SKILL = """\
---
name: test-audit
description: Gate new tests and prune redundant ones. Use when writing tests or when asked to audit or shrink a test suite.
---
Writing a test: answer first, or don't write it.
1. What observable behavior or contract does it protect?
2. What credible regression makes it fail?
3. Why doesn't existing coverage already catch it?
Never add production seams used only by tests.

Auditing (read-only until the ledger is done): mark each test by its assertions, not its name:
R retain (contract + bug it catches) · F fix a vacuous assert · C consolidate (name the absorbing test) · D delete (name the proof that remains).
Keep one test per contract, at the cheapest real boundary. Slow or static is not a reason to delete.
Before deleting, break the production code on purpose and confirm the keeper fails; restore it.
Prefer net-negative LOC. `ws design` flags the mechanical junk (no asserts, mock-only, duplicates, sleeps).
"""

SKILLS = {"progress": PROGRESS_SKILL, "test-audit": TEST_AUDIT_SKILL}
