"""Render a walked argparse tree (see ``walker.py``) as a zsh completion function.

The script is static data plus a small resolver: tables keyed by command path
(``_``, ``_ telemetry``, ``_ telemetry report``) and a loop that finds the deepest
known path among the words typed so far. Nothing runs Python on <TAB>.
"""

from __future__ import annotations

import re
from typing import Any

HELP_WIDTH = 80

FUNCTION = """
  local node=_ word prev=${words[CURRENT-1]} i
  for (( i = 2; i < CURRENT; i++ )); do
    word=${words[i]}
    if (( ${+vals[$node $word]} )); then (( i++ )); continue; fi
    [[ $word == -* ]] && continue
    (( ${+subs[$node $word]} )) && node="$node $word"
  done
  if (( ${+vals[$node $prev]} )); then
    if [[ -n ${vals[$node $prev]} ]]; then
      local -a values=(${=vals[$node $prev]}); compadd -a values
    else
      _files
    fi
    return
  fi
  if [[ ${words[CURRENT]} == -* ]]; then
    local -a options=(${(f)opts[$node]}); _describe -t options option options
    return
  fi
  local -a commands=(${(f)subs[$node]}) choices=(${=pos[$node]})
  (( $#commands )) && _describe -t commands command commands
  (( $#choices )) && compadd -a choices
  (( $#commands + $#choices )) || _files
"""


def _quote(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


def _help(text: str) -> str:
    clean = re.sub(r"\s+", " ", text.replace("%%", "%")).strip()
    return clean if len(clean) <= HELP_WIDTH else clean[: HELP_WIDTH - 1] + "…"


def _entry(name: str, help_text: str) -> str:
    """One `_describe` item: `name:description`, colons in the name escaped."""
    label = name.replace(":", r"\:")
    return f"{label}:{_help(help_text)}" if help_text else label


def _tables(node: dict[str, Any], key: str, tables: dict[str, dict[str, str]]) -> None:
    subcommands = node.get("subcommands", [])
    # `subs[key]` doubles as "this path exists" for the resolver, even when empty.
    tables["subs"][key] = "\n".join(_entry(s["name"], s.get("help", "")) for s in subcommands)
    _option_tables(node.get("options", []), key, tables)
    choices = [c for p in node.get("positionals", []) for c in p.get("choices", [])]
    if choices:
        tables["pos"][key] = " ".join(choices)
    for sub in subcommands:
        _tables(sub, f"{key} {sub['name']}", tables)


def _option_tables(options: list[dict], key: str, tables: dict[str, dict[str, str]]) -> None:
    """`opts[key]` lists every flag; `vals[key flag]` marks flags that take a value."""
    tables["opts"][key] = "\n".join(
        _entry(flag, option.get("help", "")) for option in options for flag in option["flags"]
    )
    for option in options:
        if option.get("value"):
            for flag in option["flags"]:
                tables["vals"][f"{key} {flag}"] = " ".join(option.get("choices", []))


def render(tree: dict[str, Any], *, source: str = "ai-governance") -> str:
    prog = tree["name"]
    tables: dict[str, dict[str, str]] = {"subs": {}, "opts": {}, "vals": {}, "pos": {}}
    _tables(tree, "_", tables)
    lines = [
        f"#compdef {prog}",
        f"# Generated by {source} from the {prog} argparse tree; regenerated on install/update.",
        "",
        f"_{prog}() {{",
        "  local -A subs opts vals pos",
    ]
    for name, table in tables.items():
        pairs = " ".join(f"{_quote(k)} {_quote(v)}" for k, v in table.items())
        lines.append(f"  {name}=({pairs})")
    lines.append(FUNCTION.strip("\n"))
    lines += ["}", "", f'_{prog} "$@"', ""]
    return "\n".join(lines)
